[package]
name = "deoption_derive"
version = "0.1.0"
authors = ["picklenerd <jordan.t.grace@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.30", features = ["extra-traits"] }
quote = "0.6.11"